### ISSUE TITLE
Opening config.json file without closing it?

### ISSUE THREAD

**Issue by tonmoy71** [NerdCats/ShadowCat#1]
In the load_config.py, the configuration config.json is opened without closing the resource. I don't know much about Python but there is an interesting discussion going on file opening and closing.
http://stackoverflow.com/questions/7395542/is-explicitly-closing-files-important

**Comment by Shaphil** [comment]
Fahim, in the post you referred to, the question was whether not using `close()`, or `try-finally` or `with` is a bad idea. In my case I have adopted the third solution of using the `with` which ensures the file will be closed as soon as it goes out of scope. Please see the last examples in the following:
1. [https://docs.python.org/2/tutorial/inputoutput.html#methods-of-file-objects](url)
2. [https://docs.python.org/2/howto/doanddont.html#exceptions](url)
